version: '3.7'
services:
  web:
    image: node:16
    command: bash -c "yarn dev"
    ports:
      - $PORT:$PORT
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - app-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DEV_DB_PASSWORD
      POSTGRES_DB: $DEV_DB_NAME

volumes:
  app-db:
