version: '3.7'
services:
  web:
    build: .
    image: app
    command: bash -c "yarn start"
    working_dir: /app

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
